site_name: LocalAdmin
site_url: https://localadmin.github.io/
site_author: machariasam
#repo_url: https://github.com/machariasam/localadmin
theme:
  name: material

nav:
  - Home: index.md
#  - Contact: 'contact.md'
  - About: 'about.md'
  - Installation Guides:
    - GenieACS on Ubuntu 24.04: 'genieacs.md'
    - Linux: 'linux.md'
    - Docker: 'docker.md'
    - Openstack: 'openstack.md'
